<?php

namespace backend\controllers;

use backend\models\Product;
use backend\models\Uzcassa;
use common\helpers\Curl;
use Yii;

/**
 * билеты
 */
class ProductController extends BaseController
{
    public $modelClass = Product::class;


    public function actions()
    {
        $actions = parent::actions();

        unset($actions['index']);

        return $actions; // TODO: Change the autogenerated stub
    }

    // копирование в локальную БД в таблицу product всех товаров компании из API
    public function actionCopy()
    {

        if ($token = Uzcassa::getToken()) {

            /**  результат запроса: api/product/page
            "id" : 4346,
            "branchId" : 0,
            "barcode" : "5010677160322",
            "name" : "Bacardi 35% Oakheart Original 0.7л",
            "model" : "35% Oakheart Original",
            "vatRate" : "0.00", //Ставка НДС в %
            "salesPrice" : "0.00", //Цена
            "hasExcise" : false, //С акцизом
            "exciseAmount" : null //Сумма акциза
             */

            $result = Curl::run('/api/products/page?size=1000', 'get', $token);

            if (isset($result['totalElements']) && $result['totalElements']>0) {

                // создание терминалов в системе
                foreach ($result['content'] as $item){
                  //  d($item,1);
                    $product = new Product();
                    $product->productID = (string)$item['id'];
                    $product->name = $item['name'];
                    $product->nds = $item['vatRate'];
                    if(!$product->save()){
                        d($product->getErrors(),1);
                    }
                }
                //d($result,1);

                return $result;
            }
            //d(count($result['data']));
            return $result;

        }

        return ['status' => 0, 'errors' => 'Товары не найдены!'];

    }

    // список всех товаров компании из API
    public function actionList()
    {
        if ($token = Uzcassa::getToken()) {

          /**

           */

            $result = Curl::run('/api/products/page?size=1000', 'get', $token);
            if (isset($result['totalElements'])) {
                return $result;
            }
        }

        return ['status' => 0, 'errors' => 'Товар не найден!'];

    }
}
