<?php

namespace backend\controllers;

use backend\models\Terminal;
use backend\models\Ticket;
use backend\models\Uzcassa;
use common\helpers\Curl;
use Yii;

/**
 * билеты
 */
class TerminalController extends BaseController
{
    public $modelClass = Terminal::class;


    public function actions()
    {
        $actions = parent::actions();

        unset($actions['index']);

        return $actions; // TODO: Change the autogenerated stub
    }

    // копирование в локальную БД в таблицу terminal всех терминалов компании
    public function actionCopy()
    {
        if ($token = Uzcassa::getToken()) {

            /**  результат запроса: api/terminal
             * {
             * "content": [
             * {
             * "id": 45460248,
             * "createdBy": "998946968835",
             * "createdDate": "2021-01-08T16:59:56.198",
             * "lastModifiedBy": "998946968835",
             * "lastModifiedDate": "2021-01-08T16:59:56.198",
             * "terminalId": null,
             * "serialNumber": "ффф",
             * "model": "string",
             * "branchId": 95149,
             * "branchName": "YANGI TEXNOLOGIYALAR ILMIY-AXBOROT MARKAZI",
             * "branchAddress": "Чиланзар, -",
             * "companyId": 95148,
             * "companyName": "Test",
             * "companyInn": "201589463",
             * "companyAddress": "МУКИМИЙ 166888"
             * },
             * {
             * "id": 45460247,
             * "createdBy": "998946968835",
             * "createdDate": "2021-01-08T16:59:40.483",
             * "lastModifiedBy": "998946968835",
             * "lastModifiedDate": "2021-01-08T16:59:40.483",
             * "terminalId": null,
             * "serialNumber": "string",
             * "model": "string",
             * "branchId": 95149,
             * "branchName": "YANGI TEXNOLOGIYALAR ILMIY-AXBOROT MARKAZI",
             * "branchAddress": "Чиланзар, -",
             * "companyId": 95148,
             * "companyName": "Test",
             * "companyInn": "201589463",
             * "companyAddress": "МУКИМИЙ 166888"
             * }
             * ],
             * "pageable": {
             * "sort": {
             * "sorted": false,
             * "unsorted": true,
             * "empty": true
             * },
             * "pageSize": 20,
             * "pageNumber": 0,
             * "offset": 0,
             * "paged": true,
             * "unpaged": false
             * },
             * "totalElements": 7,
             * "last": true,
             * "totalPages": 1,
             * "first": true,
             * "sort": {
             * "sorted": false,
             * "unsorted": true,
             * "empty": true
             * },
             * "numberOfElements": 7,
             * "size": 20,
             * "number": 0,
             * "empty": false
             * }
             */

            $result = Curl::run('/api/terminal?size=1000', 'get', $token);
            if (isset($result['totalElements']) && $result['totalElements']>0) {

                // создание терминалов в системе
                foreach ($result['content'] as $item){
                  //  d($item,1);
                    $terminal = new Terminal();
                    $terminal->terminalID = (string)$item['id']; //$item['terminalId'];
                    $terminal->terminalSN = $item['serialNumber'];
                    $terminal->terminalModel = $item['model'];
                    $terminal->branch_id = $item['branchId'];
                    $terminal->company_id = $item['companyId'];
                    if(!$terminal->save()){
                        d($terminal->getErrors(),1);
                    }
                }
                //d($result,1);

                return $result;
            }
            //d(count($result['data']));
            return $result;

        }

        return ['status' => 0, 'errors' => 'Терминалы не найдены!'];

    }

    // список всех терминалов компании из API
    public function actionList()
    {
        if ($token = Uzcassa::getToken()) {

            /**  результат запроса: api/terminal
             * {
             * "content": [
             * {
             * "id": 45460248,
             * "createdBy": "998946968835",
             * "createdDate": "2021-01-08T16:59:56.198",
             * "lastModifiedBy": "998946968835",
             * "lastModifiedDate": "2021-01-08T16:59:56.198",
             * "terminalId": null,
             * "serialNumber": "ффф",
             * "model": "string",
             * "branchId": 95149,
             * "branchName": "YANGI TEXNOLOGIYALAR ILMIY-AXBOROT MARKAZI",
             * "branchAddress": "Чиланзар, -",
             * "companyId": 95148,
             * "companyName": "Test",
             * "companyInn": "201589463",
             * "companyAddress": "МУКИМИЙ 166888"
             * },
             * {
             * "id": 45460247,
             * "createdBy": "998946968835",
             * "createdDate": "2021-01-08T16:59:40.483",
             * "lastModifiedBy": "998946968835",
             * "lastModifiedDate": "2021-01-08T16:59:40.483",
             * "terminalId": null,
             * "serialNumber": "string",
             * "model": "string",
             * "branchId": 95149,
             * "branchName": "YANGI TEXNOLOGIYALAR ILMIY-AXBOROT MARKAZI",
             * "branchAddress": "Чиланзар, -",
             * "companyId": 95148,
             * "companyName": "Test",
             * "companyInn": "201589463",
             * "companyAddress": "МУКИМИЙ 166888"
             * }
             * ],
             * "pageable": {
             * "sort": {
             * "sorted": false,
             * "unsorted": true,
             * "empty": true
             * },
             * "pageSize": 20,
             * "pageNumber": 0,
             * "offset": 0,
             * "paged": true,
             * "unpaged": false
             * },
             * "totalElements": 7,
             * "last": true,
             * "totalPages": 1,
             * "first": true,
             * "sort": {
             * "sorted": false,
             * "unsorted": true,
             * "empty": true
             * },
             * "numberOfElements": 7,
             * "size": 20,
             * "number": 0,
             * "empty": false
             * }
             */

            $result = Curl::run('/api/terminal', 'get', $token);
            if (isset($result['totalElements'])) {
                return $result;
            }
        }

        return ['status' => 0, 'errors' => 'Терминал не найден!'];

    }
}
